### ISSUE TITLE
Create a license for this repository

### ISSUE THREAD

**Issue by garzarobm** [Robjects-Collaborations/WhatIsMyAdaptor#4]
- [x] Use basic structure of a good license (MIT, BSD, etc.,)
- [x] Put some basic README.md content tying to it.

**Comment by umer936** [comment]
I generally use the MIT license or the WTFPL - prefer MIT.

**Comment by garzarobm** [comment]
Sounds good to me, I'll use the MIT license

**Comment by garzarobm** [comment]
All tasks have been completed for Issue, and issue is closing. For other licensing issues, feel free to open a new one.
